name: Gordon Armour
favicon: null
layout_spectrum: 0.9480398101732135
typography_spectrum: 0.14912874554283917
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#84d2f9'
    - '#333426'
    - '#80837a'
    - '#d0d0c4'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.857149331830442
  rhythmicContrast: 0.37302105338312685
purpose: []
